### ISSUE TITLE
Redundant check in `op` macro

### ISSUE THREAD

**Issue by ohAitch** [kparc/ksimple#4]
https://github.com/kparc/ksimple/blob/948c820b5668c0c77f1176249e017b3316742816/a.c#L97
For `N(nx,(ax?x:sx[i]) OP sf[i]))`, aren't we already in the `!ax` branch, with a+v `N(nx,f OP xi)` handled earlier?

**Comment by kelas** [comment]
oh, true. i originally had both cases stuffed into same loop, then decided to separate a+v for clarity, and forgot to clean up the tail. fix is coming.

thanks.

**Comment by kelas** [comment]
fixed, thanks again.
